fix bug which causes arguments not properly with slash commands
the line has "2x star" which caused slash commands not properly parse the arguments

error log:

```
Traceback (most recent call last):
  File "/home/linux/.local/lib/python3.8/site-packages/discord_slash/client.py", line 1186, in invoke_command
    await func.invoke(ctx, **args)
  File "/home/linux/.local/lib/python3.8/site-packages/discord_slash/model.py", line 210, in invoke
    return await self.func(*args, **kwargs)
TypeError: execute() got an unexpected keyword argument 'url'
```

after i removed it everything worked perfectly fine.