updating sub_command cmd second_option part
There is a "TypeError: run.<locals>.cmd() missing 1 required positional argument: 'second_option'" problem in sub_commands example code
so fixing second_option: str to second_option:str = ""