changing sub commands example code
part of sub commands make trouble in python 3.10 above the error occur 
TypeError: run.<locals>.cmd() missing 1 required positional argument: 'second_option'